---
- hosts: localhost
  connection: local
  vars:
    key_name: my-ec2-keypair
    region: ap-south-1
  tasks:
    - name: Create EC2 key pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: present
      register: keypair

    - name: Save private key
      copy:
        content: "{{ keypair.key.private_key }}"
        dest: "~/.ssh/{{ key_name }}.pem"
        mode: 0600
