
#follow URL https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.htmlhttps://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
- name: Create security group in Mumbai region
  hosts: localhost
  gather_facts: no
  vars:
    region: ap-south-1
    security_group_name: my-security-group
    security_group_description: My security group
    security_group_rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0
  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        region: "{{ region }}"
        rules: "{{ security_group_rules }}"
        vpc_id: "{{ vpc_id }}"
      register: result

    - name: Show security group id
      debug:
        var: result.group_id
